name: AI Foundry Model Evaluator

on:
  workflow_call:
  workflow_dispatch:  

permissions:
  contents: read
  id-token: write

jobs:
  evaluate:
    name: Run AI Foundry Model Evaluations
    runs-on: ubuntu-latest
    env: 
      # GENAI_EVALS_CONFIG_PATH: ${{ github.workspace }}/evaluate-config.json 
      # GENAI_EVALS_DATA_PATH: ${{ github.workspace }}/.github/.test_files/eval-input.jsonl
      GENAI_EVALS_CONFIG_PATH: ${{ github.workspace }}/evals/results/baseline/config.json 
      GENAI_EVALS_DATA_PATH: ${{ github.workspace }}/evals/results/baseline/eval_results.jsonl
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          #creds: ${{ secrets.AZURE_CREDENTIALS }}
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Set az account
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az account set --subscription ${{env.AZURE_SUBSCRIPTION_ID}}

      - name: Login to with Azure with azd (Federated Credentials)
        run: |
          azd auth login `
            --client-id "$Env:AZURE_CLIENT_ID" `
            --federated-credential-provider "github" `
            --tenant-id "$Env:AZURE_TENANT_ID"
        shell: pwsh

      - name: Write evaluate config
        run: |
          cat > ${{ env.GENAI_EVALS_CONFIG_PATH }} <<EOF
          {
            "data": "${{ env.GENAI_EVALS_DATA_PATH }}",
            "evaluators": {
              "coherence": "CoherenceEvaluator",
              "fluency": "FluencyEvaluator"
            },
            "ai_model_configuration": {
              "type": "azure_openai",
              "azure_endpoint": "https://${{ secrets.AZURE_OPENAI_SERVICE }}".openai.azure.com",
              "azure_deployment": "${{ secrets.AZURE_OPENAI_CHAT_DEPLOYMENT }}"           
            }
          }
          EOF
      - name: Run Model Evaluation
        id: run-model-evaluation
        uses: microsoft/genai-evals@main
        with:
          evaluate-configuration: ${{ env.GENAI_EVALS_CONFIG_PATH }}
          show-summary: true
          show-raw-output: true


            # "ai_model_configuration": {
            #   "type": "azure_openai",
            #   "azure_endpoint": "${{ secrets.AZURE_OPENAI_ENDPOINT }}",
            #   "azure_deployment": "${{ secrets.AZURE_OPENAI_CHAT_DEPLOYMENT }}",
            #   "api_key": "${{ secrets.AZURE_OPENAI_API_KEY }}",
            #   "api_version": "${{ secrets.AZURE_OPENAI_API_VERSION }}"
            # }